
5,$s/<token>//g
5,$s//<token>/g

### AUTH
POST http://localhost:8000/signin
Accept: application/json
Content-Type: application/json

{
  "ns": "interventions",
  "db": "demo",
  "sc": "user",
  "pass": "01HJTEBG4Y1EAXPATENCDCT7WW"
}

# on_cron
curl -sS -X POST \
  -u "root:root" \
  -H "NS: interventions" \
  -H "DB: demo" \
  -H "Accept: application/json" \
  -d "fn::on_cron('steps')" \
  http://localhost:8000/sql | jq '.[].result'
  
# on_push
curl -sS -X POST \
  -u "root:root" \
  -H "NS: interventions" \
  -H "DB: demo" \
  -H "Accept: application/json" \
  -d "fn::on_push((SELECT id, created FROM papers WHERE user = users:1 ORDER BY created DESC LIMIT 1)[0].id, []);" \
  http://localhost:8000/sql | jq '.[].result'
  
# test
-H "Authorization: Basic dXNlcm5hbWU6MTIzNDU2" \ # ?? Authorization
-H "Authorization: Basic cm9vdDpyb290" \
-u "root:root" \

curl -sS -X POST \
  -H "Authorization: Bearer <token>" \
  -H "NS: interventions" \
  -H "DB: demo" \
  -H "Accept: application/json" \
  -d "fn::on_push(<papers:id>)" \
  http://localhost:8000/sql | jq '.[].result'
  
#
