
GET http://localhost:8000/key/answers
NS: test
DB: outcomes
Accept: application/json

GET http://localhost:8000/key/outcomes
NS: test
DB: outcomes
Accept: application/json

GET http://localhost:8000/key/records
NS: test
DB: outcomes
Accept: application/json

GET http://localhost:8000/key/scripts
NS: test
DB: outcomes
Accept: application/json

## 

PATCH http://localhost:8000/key/outcomes/1
NS: test
DB: outcomes
Accept: application/json
Content-Type: application/json

{
  "user": "users:1",
  "resource": "resources:1",
  "answers": ["answers:1", "answers:2"]
}
