
GET http://localhost:8000/key/answers
NS: main
DB: outcome
Accept: application/json

GET http://localhost:8000/key/papers
NS: main
DB: outcome
Accept: application/json

GET http://localhost:8000/key/records
NS: main
DB: outcome
Accept: application/json

GET http://localhost:8000/key/scripts
NS: main
DB: outcome
Accept: application/json

## 

PATCH http://localhost:8000/key/papers/1
NS: main
DB: outcome
Accept: application/json
Content-Type: application/json

{
  "user": "users:1",
  "resource": "resources:1",
  "answers": ["answers:1", "answers:2"]
}
