
5,$s/<token>//g
5,$s//<token>/g

POST http://localhost:8000/signin
Accept: application/json
Content-Type: application/json

{
  "ns": "interventions",
  "db": "demo",
  "sc": "user",
  "pass": "01HJTEBG4Y1EAXPATENCDCT7WW"
}

## pass ⬇️
GET http://localhost:8000/key/scripts
Accept: application/json
Authorization: Bearer <token>

GET http://localhost:8000/key/scripts/1
Accept: application/json
Authorization: Bearer <token>

## fails ⬇️
GET http://localhost:8000/key/scripts
Accept: application/json

DELETE http://localhost:8000/key/scripts/1
Accept: application/json
Authorization: Bearer <token>

POST http://localhost:8000/key/scripts
Accept: application/json
Content-Type: application/json
Authorization: Bearer <token>

{
  "code": "\nconsole.log('hello world')\n",
  "name": "foo"
}

PATCH http://localhost:8000/key/scripts/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer <token>

{
  "name": "bar"
}
