
5,$s/<token>//g
5,$s//<token>/g

### AUTH
POST http://localhost:8000/signin
Accept: application/json
Content-Type: application/json

{
  "ns": "global",
  "db": "main",
  "sc": "user",
  "username": "kenny"
}

## pass ⬇️
###
GET http://localhost:8000/key/users
Accept: application/json
Authorization: Bearer <token>

###
GET http://localhost:8000/key/users/<id>
Accept: application/json
Authorization: Bearer <token>

###
PATCH http://localhost:8000/key/users/<id>
Accept: application/json
Content-Type: application/json
Authorization: Bearer <token>

{
  "web_token": {
    "endpoint":"https://fcm.googleapis.com/fcm/send/e6mMuIMNpzw:APA91bGJaoDNMKXKIvO3oPjgUdC3kkwMihdSsAEMg1XyX6qA1yO3DpYaPuzth38foY-ER09xL6MvAALHJMcQmM9JRdt6QEh6l0Mvmvwy-yppEUVRFAIuxvdGJklbktgvqiXLz0XyjH_1",
    "keys":{
      "auth": "EFQMo1MUrpK1hkCSwtc5Dg",
      "p256dh": "BNNUAaReIYG7kd4FuQ_wC07gPTnwHk32EOqXyAqlg2GleQE91gjclxOu9kwgLfxjcak_XYEGS586H8ZcP0hBo5k"
    }
  }
}

## fails ⬇️
###
DELETE http://localhost:8000/key/users/<id>
Accept: application/json
Authorization: Bearer <token>

###
POST http://localhost:8000/key/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer <token>

{
  "username": "kenny",
  "password": "kenny",
  "project": "projects:2"
}

###
PATCH http://localhost:8000/key/users/<id>
Accept: application/json
Content-Type: application/json
Authorization: Bearer <token>

{
  "username": "perro"
}
