-- CREATE media CONTENT {
--   type: 'image',
--   url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png',
--   alt: 'Google logo',
-- }

UPDATE media:1 CONTENT { alt: 'Google logo', type: 'image', url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png' };
UPDATE media:2 CONTENT { alt: 'Youtube vídeo', type: 'video', url: 'https://www.youtube.com/watch?v=FoMlSB6ftQg' };
