
GET http://localhost:8000/key/locales
NS: main
DB: content
Accept: application/json

GET http://localhost:8000/key/media
NS: main
DB: content
Accept: application/json

GET http://localhost:8000/key/questions
NS: main
DB: content
Accept: application/json

GET http://localhost:8000/key/slides
NS: main
DB: content
Accept: application/json

GET http://localhost:8000/key/resources
NS: main
DB: content
Accept: application/json

